@startuml

title __ENTITIES's Class Diagram__\n

  namespace com.kaizen.nightfolks {
    namespace model {
      namespace entities {
        class com.kaizen.nightfolks.model.entities.Party {
            - date : Date
            - genre : String
            - host : String
            - id : long
            - name : String
            + Party()
            + Party()
            + Party()
            + Party()
            + Party()
            + Party()
            + equals()
            + getDate()
            + getGenre()
            + getHost()
            + getId()
            + getName()
            + setDate()
            + setGenre()
            + setHost()
            + setId()
            + setName()
        }
      }
    }
  }
  

  namespace com.kaizen.nightfolks {
    namespace model {
      namespace entities {
        class com.kaizen.nightfolks.model.entities.Playlist {
            {static} + CREATOR : Creator<Playlist>
            - mSongs : List<Song>
            + Playlist()
            {static} + createSongsList()
            + describeContents()
            + getSongs()
            + setSongs()
            + writeToParcel()
            # Playlist()
        }
      }
    }
  }
  

  namespace com.kaizen.nightfolks {
    namespace model {
      namespace entities {
        class com.kaizen.nightfolks.model.entities.Song {
            {static} + CREATOR : Creator<Song>
            - mPath : String
            - mTitle : String
            - mVotes : int
            + Song()
            + describeContents()
            + getPath()
            + getTitle()
            + getVotes()
            + setPath()
            + setTitle()
            + setVotes()
            + writeToParcel()
            # Song()
        }
      }
    }
  }
  

  com.kaizen.nightfolks.model.entities.Playlist .up.|> android.os.Parcelable
  com.kaizen.nightfolks.model.entities.Song .up.|> android.os.Parcelable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
